Feature/ngnix reverse proxy
mhummel-artiso/lecture-calendar pull request #4
Opened 2023-07-20 13:55 UTC by SamuelKraut

2023-07-20 14:24 UTC, mhummel-artiso commented
![image](https://github.com/mhummel-artiso/lecture-calendar/assets/73578966/bcf15bdf-47e1-46f9-ad14-b2b254865b5d)

2023-07-20 15:12 UTC, mhummel-artiso requested changes

2023-07-20 15:12 UTC, mhummel-artiso commented on docker-compose.yml
> +  nginx:
adde noch ein restart: always

2023-07-20 15:14 UTC, SamuelKraut commented on docker-compose.yml
> -    networks:
Ist es da nicht sinnvoll noch einen zweiten NGNIX zu machen? Wollte jetzt erstmal nur WebServer

2023-09-12 12:01 UTC, SamuelKraut commented on docker-compose.yml
> +  nginx:
asdasd

2023-09-12 12:02 UTC, SamuelKraut commented on docker-compose.yml
> +      - 4000:4000
sad

2023-09-27 07:31 UTC, mhummel-artiso approved these changes

2023-09-27 07:31 UTC, merged